spring.application.name=safevault

spring.datasource.url=jdbc:postgresql://localhost:5432/safevault
spring.datasource.username=safevault
spring.datasource.password=safevault

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

server.port=8080

management.endpoints.web.exposure.include=health,info

security.jwt.secret=SECRET_KEY
security.jwt.expiration=86400000