spring.application.name=safevault

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/safevault}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:safevault}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:safevault}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

server.port=8080

management.endpoints.web.exposure.include=health,info

security.jwt.secret=${SECURITY_JWT_SECRET:heWejtBlnBI82RUwcVMqUmR2Ch/4rPOL++ms4FfB1NQ=}
security.jwt.expiration=86400000
